node('nodejs8') {
  stage ('checkout') {
    checkout scm
  }
  stage ('install modules'){
    sh '''
      npm install --verbose -d
      npm install --save classlist.js
    '''
  }
  stage ('build') {
    sh '$(npm bin)/ng build --prod --build-optimizer'
  }
  stage ('build image') {
    sh '''
      cp -r nginx/. dist
      oc start-build angular-5-example --from-dir=dist --follow
    '''
  }
}
