node('nodejs') {
  stage ('checkout') {
    checkout scm
  }
  stage ('install modules'){
    sh '''
      npm install --verbose -d
      npm install --save classlist.js
    '''
  }
  stage ('build') {
    sh '$(npm bin)/ng build --prod --build-optimizer'
  }
  stage ('build image') {
    sh '''
      mkdir dist/nginx-cfg
      cp -r nginx/nginx-cfg dist
      cp -r nginx/nginx-default-cfg dist
      oc start-build angular-5-example-rhel --from-dir=dist --follow
    '''
  }
}
